### ISSUE TITLE
libstdc++ does not match Debian

### ISSUE THREAD

**Issue by Midar** [flathub/com.epicgames.ut2004#4]
The commit says the binary is from Debian, but that doesn't seem to be the case:

```
SHA256 8cf113f43661893cd9e0a94972eb53c552283b291c546384f15edc3d65375b35  libstdc++.so.5.0.7
SHA256 12b1f05db7543bc3a1651f479fc16dde85fc93a799dd91e5896676229d78ea12  usr/lib/i386-linux-gnu/libstdc++.so.5.0.7
```

First one is from the repo, second one is from https://packages.debian.org/buster/i386/libstdc++5/download. Where is this binary from?

Could it be fetched from Debian directly instead of being part of the repo?

**Comment by AsciiWolf** [comment]
It's from the latest 1:3.3.6-34 [libstdc++5](https://packages.debian.org/bookworm/libstdc++5) package version, amd64 build (since the ut2004 binary is native 64bit). I have just checked the SHA256 checksum and it matches.

```
From libstdc++5_3.3.6-34_amd64.deb:
SHA256 8cf113f43661893cd9e0a94972eb53c552283b291c546384f15edc3d65375b35  libstdc++.so.5.0.7
```

**Comment by Midar** [comment]
Any reason to not just download the .deb file during the build process and extract it?

**Comment by AsciiWolf** [comment]
Yes: My time. I am already too busy with too many other things and considering that the libstdc++5 package is deprecated in Debian, not present in testing/sid, and its last update in Bookworm was in 2022, this is not a big priority for me.

**Comment by Midar** [comment]
Fair enough, thanks.
